services:
  - type: web
    name: farm-android
    runtime: node
    plan: free
    branch: new-main
    buildCommand: cd webapp && npm install && npm run build
    startCommand: cd webapp && npx vite preview --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://farm-webapp-rezy.onrender.com
      - key: NODE_VERSION
        value: "20"
    rootDir: .
