services:
  - type: web
    name: farm-android
    runtime: node
    plan: free
    branch: new-main
    buildCommand: cd webapp && npm install && npm run build
    startCommand: cd webapp && node server.cjs
    envVars:
      - key: BACKEND_URL
        value: https://farm-webapp-rezy.onrender.com/api
      - key: NODE_VERSION
        value: "20"
    rootDir: .
